# for support join https://discord.gg/HpznVJjqwy
#applicable types - "MySQL", "h2"
storage-method: "h2"
database:
  mysql:
    host: "na01-sql.pebblehost.com"
    port: 3306
    database: ""
    username: ""
    password: ""

sound:
  enabled: true
  sound: 'ENTITY_PLAYER_LEVELUP'

shop:
  close-on-purchase: true

placeholders:
  none-active: '&cNone'
