#applicable types - "MySQL", "h2"
storage-method: "MySQL"
database:
  mysql:
    host: "na01-sql.pebblehost.com"
    port: 3306
    database: "customer_969304_perkroll"
    username: "customer_969304_perkroll"
    password: "Gb6zoJ7cz6cG^4v@MChWiBkc"

tillGuaranteed:
  amount: 100
  rarity: 'Master'

perks:
  attack:
    rarity: 'Basic'
    levels:
      1:
        chance: '40'
        boosts:
          1:
            type: 'currency'
            boost: 'Shard'
            amount: '5' # This is the percentage boost
