name: PerkRoll
version: '${project.version}'
main: me.frxq.perkroll.PerkRoll
api-version: 1.18
author: frxq
description: PerkRoll is an advanced perk rolling system that allows players to customize and enhance their gameplay experience with unique perks and abilities.
softdepend:
  - EdDungeons

commands:
  perkroll:
    usage: '/perkroll <subcommand>'
    description: 'Main command for perkroll'
    aliases: [pr]
  perks:
    usage: '/perks'
    description: 'Open the perks menu'
  payperks:
    usage: '/payperks <player> <amount>'
    description: 'Pay perks to another player'